Traceback (most recent call last):
  File "E:/python-jianshu/ÀàºÍ¶ÔÏó.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 68, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
Traceback (most recent call last):
  File "E:/python-jianshu/ç±»å’Œå¯¹è±¡.py", line 69, in <module>
    print(dog1.name)
AttributeError: 'Dog' object has no attribute 'name'
